services:
  - type: web
    name: future-academy-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://future-academy-web.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: future-academy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: future-academy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: future-academy-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: future-academy-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: future-academy-db
          property: password
      - key: PORT
        value: 10000
    dependsOn:
      - future-academy-db

  - type: pserv
    name: future-academy-db
    plan: free
    env: postgres
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
